app.py
import os
from engine import create_app
from dotenv import load_dotenv

load_dotenv()

app = create_app()

if __name__ == '__main__':
   app.run()

engine/__init__.py
from flask import Flask
from flask_cors import CORS
import os

def create_app():
    parentDir = os.path.abspath(os.path.join(os.path.dirname(__name__),".."))
    app = Flask(parentDir)
    if os.environ.get('FLASK_ENV') == 'development':
        CORS(app)
    from engine.api.routes import api_blueprint
    app.register_blueprint(api_blueprint)
    return app

engine/api/__init__.py
from flask import Blueprint

api_blueprint = Blueprint('engine', __name__)

from . import routes

engine/api/routes.py
from . import api_blueprint
import os
from flask import request, jsonify, Response, stream_with_context, json
from flask import redirect, render_template, send_from_directory, url_for
from flask import session

## import requests
## import sseclient
from engine.services import openai_service, vector_service, lawyer_service
from engine.utils.helper_functions import chunk_text, build_prompt, construct_messages_list

@api_blueprint.route('/')
def index():
   print('Request for index page received')
   return render_template('index.html')

@api_blueprint.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(".", 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')

@api_blueprint.route('/engine.hello', methods=['POST'])
def hello():
   name = request.form.get('name')

   if name:
       print('Request for MountainAvens received with name=%s' % name)
       return render_template('hello.html', name = name)
   else:
       print('Request MountainAvens received with no name or blank name -- redirecting')
       return redirect(url_for('index'))


@api_blueprint.route('/handle-query', methods=['POST'])
def handle_query():
    name = request.form.get('question')
    chat_history = None # TODO: get it from session
    
    # Get the most similar chunks from Pinecone
    #context_chunks = pinecone_service.get_most_similar_chunks_for_query(question, PINECONE_INDEX_NAME)
    
    # Build the payload to send to OpenAI
    #headers, data = openai_service.construct_llm_payload(question, context_chunks, chat_history)

    # Send to OpenAI's LLM to generate a completion
    def generate():
        #url = 'https://api.openai.com/v1/chat/completions'
        #response = requests.post(url, headers=headers, data=json.dumps(data), stream=True)
        #client = sseclient.SSEClient(response)
        #for event in client.events():
        #    if event.data != '[DONE]':
        #        try:
        #            text = json.loads(event.data)['choices'][0]['delta']['content']
        #            yield(text)
        #        except:
        #            yield('')
        response = "our smart legal advice here..."
        for c in response:
            yield(c)
    
    # Return the streamed response from the LLM to the frontend
    return Response(stream_with_context(generate()))

""""
@api_blueprint.route('/embed-and-store', methods=['POST'])
def embed_and_store():
    url = request.json['url']
    url_text = scraping_service.scrape_website(url)
    chunks = chunk_text(url_text)
    pinecone_service.embed_chunks_and_upload_to_pinecone(chunks, PINECONE_INDEX_NAME)
    response_json = {
        "message": "Chunks embedded and stored successfully"
    }
    return jsonify(response_json)

@api_blueprint.route('/delete-index', methods=['POST'])
def delete_index():
    pinecone_service.delete_index(PINECONE_INDEX_NAME)
    return jsonify({"message": f"Index {PINECONE_INDEX_NAME} deleted successfully"})
"""

templates/hello.html
<!doctype html>
<head>
    <title>MountainAvens MyAILegalOffice</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<html>
   <body>
     <main>
        <div class="px-4 py-3 my-2 text-center">
            <img class="d-block mx-auto mb-4" src="{{ url_for('static', filename='images/azure-icon.svg') }}" alt="Azure Logo" width="192" height="192"/>
            <!-- <img  src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
            <h1 class="display-6 fw-bold">Hello {{name}}</h1>
            <p class="fs-5">
                What is your request?
            </p>
            <form method="post" action="{{url_for('engine.handle_query')}}">
              <div class="col-md-6 mx-auto text-center">
                  <label for="question" class="form-label fw-bold fs-5">question</label>
                  <!-- <p class="lead mb-2">question</p> -->
                  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center align-items-center my-1">
                      <input type="text" class="form-control" id="question" name="question" style="max-width: 256px;">
                    </div>            
              </div>
          </form>
  
            <a href="{{ url_for('engine.index') }}" class="btn btn-primary btn-lg px-4 gap-3">Back home</a>
          </div>
     </main>      
   </body>
</html>

templates/index.html
<!doctype html>
<head>
    <title>MountainAvens</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<html>
   <body>
     <main>
        <div class="px-4 py-3 my-2 text-center">
            <img class="d-block mx-auto mb-4" src="{{ url_for('static', filename='images/azure-icon.svg') }}" alt="Azure Logo" width="192" height="192"/>
            <!-- <img  src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
            <h1 class="display-6 fw-bold text-primary">My AI Legal Office</h1>            
          </div>
        <form method="post" action="{{url_for('engine.hello')}}">
            <div class="col-md-6 mx-auto text-center">
                <label for="name" class="form-label fw-bold fs-5">Login</label>

                <!-- <p class="lead mb-2">Username</p> -->
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center align-items-center my-1">
                    <input type="text" class="form-control" id="name" name="name" style="max-width: 256px;">
                  </div>            
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center my-2">
                  <button type="submit" class="btn btn-primary btn-lg px-4 gap-3">Start session</button>
                </div>            
            </div>
        </form>
     </main>      
   </body>
</html>